keys:
  - &meow age1l9xmv38zy3mrqs3qy7m9ufw38gceetz9yumr5jzl92tgtt9mmgzse2a4p0
  - &woof age1zshceez6xw8yule6wcwcrpvedn4vhtw0rgxk0fqepfx046ycuersrzlrw6
creation_rules:
  - path_regex: '^secrets/msi-laptop/.*\.(yaml|yml|json|env|ini)$'
    key_groups:
      - age:
        - *meow
  - path_regex: '^secrets/server/.*\.(yaml|yml|json|env|ini)$'
    key_groups:
      - age:
        - *woof
  - path_regex: '^modules/services/.*\.(yaml|yml|json|env|ini)$'
    key_groups:
      - age:
        - *woof
