source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/autostart.conf

source = ~/.config/hypr/conf/env_variables.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf

source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/window.conf
