name: Build & Push jocimsus

on:
  push:
    branches:
      - workflow-patching

jobs:
  build:
    name: Build and Push Config
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@v15
        with:
          name: jocimsus
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: x86_64-linux Build
        if: matrix.os == 'ubuntu-latest'
        run: nix build .#{prismlauncher,devShells.x86_64-linux.{c_dev}}
      - name: Deploy
        run: |
          cachix push jocimsus ./result*
