name: Check, Build, and Push Flake Config to Cachix

env:
  EXTRA_NIX_CONFIG: |
    auto-optimise-store = true
    experimental-features = nix-command flakes
    max-jobs = auto
    download-buffer-size = 500000000
    substituters = https://jocimsus.cachix.org https://cache.nixos.org https://nix-community.cachix.org https://prismlauncher.cachix.org
    trusted-public-keys = jocimsus.cachix.org-1:JLglEO54KxFNzvLZlz6MxvYap/7gJLK0w+jT8GRHrXw= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= prismlauncher.cachix.org-1:9/n/FGyABA2jLUVfY+DEp4hKds/rwO+SCOtbOkDzd+c=

on:
  push:
    branches:
      - workflows
